backend:
  name: github
  repo: unna-tech/blog
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/images"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Current", name: "current", widget: "hidden", default: "post"}
      - {label: "Navigation", name: "navigation", widget: "hidden", default: "True"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Main Class", name: "main-class", widget: "select", options: ["jekyll", "css", "js", "html", "svg", "dev", "misc"]}
      - {label: "Tags", name: "tags", widget: "list", default: [""]}
      - {label: "Category", name: "categories", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}